export const project = [
	{
		id: 1,
		title: "Portfolio Project",
		body: "example content",
		image: "/logo512.png",
		link: "https://github.com/jnewton25/Portfolio",
		demo: "https://github.com/jnewton25/Portfolio",
	},
	{
		id: 2,
		title: "To Do List - React",
		body: "example content",
		image: "/logo512.png",
		link: "https://github.com/jnewton25/to-do-list",
		demo: "https://github.com/jnewton25/to-do-list",
	},
	{
		id: 3,
		title: "Guesteaus",
		body: "example content",
		image: "/logo512.png",
		link: "https://github.com/jnewton25/Gusteaus",
		demo: "https://github.com/jnewton25/Gusteaus",
	},
	{
		id: 4,
		title: "Mos Eisley Restaurant",
		body: "example content",
		image: "/logo512.png",
		link: "https://github.com/jnewton25/MosEisley",
		demo: "https://github.com/jnewton25/MosEisley",
	},
	{
		id: 5,
		title: "FreeCodeCamp Portfolio Project",
		body: "example content",
		image: "/logo512.png",
		link: "https://github.com/jnewton25",
		demo: "https://github.com/jnewton25",
	},
	{
		id: 6,
		title: "Valorant Survey Form",
		body: "example content",
		image: "/logo512.png",
		link: "https://github.com/jnewton25",
		demo: "https://github.com/jnewton25",
	},
	{
		id: 7,
		title: "Landing Page Project",
		body: "example content",
		image: "/logo512.png",
		link: "https://github.com/jnewton25",
		demo: "https://github.com/jnewton25",
	},
];
